/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ClinicFlow Design System — sourced from Stitch-generated Tailwind config
        "primary":                    "#005c55",
        "on-primary":                 "#ffffff",
        "primary-container":          "#0f766e",
        "on-primary-container":       "#a3faef",
        "primary-fixed":              "#9cf2e8",
        "primary-fixed-dim":          "#80d5cb",
        "on-primary-fixed":           "#00201d",
        "on-primary-fixed-variant":   "#00504a",
        "secondary":                  "#006b5e",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#96f3e1",
        "on-secondary-container":     "#007164",
        "secondary-fixed":            "#96f3e1",
        "secondary-fixed-dim":        "#7ad7c6",
        "on-secondary-fixed":         "#00201b",
        "on-secondary-fixed-variant": "#005046",
        "tertiary":                   "#4f5254",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#676a6c",
        "on-tertiary-container":      "#e9ebed",
        "tertiary-fixed":             "#e0e3e5",
        "tertiary-fixed-dim":         "#c4c7c9",
        "on-tertiary-fixed":          "#191c1e",
        "on-tertiary-fixed-variant":  "#444749",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "surface":                    "#f7faf8",
        "surface-dim":                "#d7dbd9",
        "surface-bright":             "#f7faf8",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f1f4f3",
        "surface-container":          "#ebefed",
        "surface-container-high":     "#e5e9e7",
        "surface-container-highest":  "#e0e3e1",
        "surface-variant":            "#e0e3e1",
        "on-surface":                 "#181c1c",
        "on-surface-variant":         "#3e4947",
        "surface-tint":               "#006a63",
        "background":                 "#f7faf8",
        "on-background":              "#181c1c",
        "outline":                    "#6e7977",
        "outline-variant":            "#bdc9c6",
        "inverse-surface":            "#2d3130",
        "inverse-on-surface":         "#eef1f0",
        "inverse-primary":            "#80d5cb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm:      "0.25rem",
        md:      "0.375rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        "base":          "4px",
        "xs":            "8px",
        "sm":            "16px",
        "md":            "24px",
        "lg":            "32px",
        "xl":            "48px",
        "sidebar-width": "260px",
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg":  ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg":     ["Inter", "sans-serif"],
        "body-md":     ["Inter", "sans-serif"],
        "body-sm":     ["Inter", "sans-serif"],
        "label-md":    ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg":  ["48px",  { lineHeight: "56px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px",  { lineHeight: "40px",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px",  { lineHeight: "32px",  fontWeight: "600" }],
        "body-lg":     ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":     ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "body-sm":     ["14px",  { lineHeight: "20px",  fontWeight: "400" }],
        "label-md":    ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
