/**
 * Production Nginx Reverse Proxy Builder
 * Generates enterprise-grade Nginx configuration with TLS 1.3, HTTP/2, rate-limiting,
 * security headers, and WebSocket sync support for ClinicFlow API.
 */

export interface NginxConfigOptions {
  domainName?: string;
  upstreamHost?: string;
  upstreamPort?: number;
  sslCertPath?: string;
  sslKeyPath?: string;
  rateLimitReqPerSec?: number;
  rateLimitBurst?: number;
  clientMaxBodySizeMb?: number;
  enableGzip?: boolean;
  webSocketPath?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export class NginxConfigBuilder {
  private domainName: string;
  private upstreamHost: string;
  private upstreamPort: number;
  private sslCertPath: string;
  private sslKeyPath: string;
  private rateLimitReqPerSec: number;
  private rateLimitBurst: number;
  private clientMaxBodySizeMb: number;
  private enableGzip: boolean;
  private webSocketPath: string;

  constructor(options: NginxConfigOptions = {}) {
    this.domainName = options.domainName || 'api.clinicflow.pk';
    this.upstreamHost = options.upstreamHost || '127.0.0.1';
    this.upstreamPort = options.upstreamPort || 3001;
    this.sslCertPath = options.sslCertPath || '/etc/letsencrypt/live/api.clinicflow.pk/fullchain.pem';
    this.sslKeyPath = options.sslKeyPath || '/etc/letsencrypt/live/api.clinicflow.pk/privkey.pem';
    this.rateLimitReqPerSec = options.rateLimitReqPerSec || 30;
    this.rateLimitBurst = options.rateLimitBurst || 20;
    this.clientMaxBodySizeMb = options.clientMaxBodySizeMb || 25;
    this.enableGzip = options.enableGzip ?? true;
    this.webSocketPath = options.webSocketPath || '/api/v1/sync';
  }

  public generateConfig(): string {
    return `# ==============================================================================
# ClinicFlow Production Reverse Proxy Configuration
# Auto-generated by NginxConfigBuilder
# Target: Ubuntu 22.04 LTS / VPS Hostinger
# ==============================================================================

# Rate Limiting Zone Definition
limit_req_zone $binary_remote_addr zone=clinicore_api_limit:10m rate=${this.rateLimitReqPerSec}r/s;
limit_conn_zone $binary_remote_addr zone=clinicore_conn_limit:10m;

upstream clinicore_backend {
    server ${this.upstreamHost}:${this.upstreamPort} max_fails=3 fail_timeout=10s;
    keepalive 32;
}

# HTTP to HTTPS Redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${this.domainName};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Primary HTTPS Production Server Unit
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${this.domainName};

    # TLS 1.3 & 1.2 Enterprise Encryption Suite
    ssl_certificate ${this.sslCertPath};
    ssl_certificate_key ${this.sslKeyPath};
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # Security Hardening Headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline';" always;

    # General Request Constraints
    client_max_body_size ${this.clientMaxBodySizeMb}M;
    client_body_timeout 15s;
    client_header_timeout 15s;
    keepalive_timeout 65s;

    # Performance Compression
    ${this.enableGzip ? `gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;` : '# Gzip disabled'}

    # Root Health check endpoint
    location /health {
        proxy_pass http://clinicore_backend/health;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        access_log off;
    }

    # Real-Time WebSocket Sync Endpoint
    location ${this.webSocketPath} {
        proxy_pass http://clinicore_backend${this.webSocketPath};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket Timeout Tuning (24-hour sync support)
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Core API Gateway Routing
    location / {
        limit_req zone=clinicore_api_limit burst=${this.rateLimitBurst} nodelay;
        limit_conn clinicore_conn_limit 20;

        proxy_pass http://clinicore_backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;
        proxy_send_timeout 30s;
    }
}
`;
  }

  public validateConfig(configContent?: string): ValidationResult {
    const content = configContent || this.generateConfig();
    const errors: string[] = [];
    const warnings: string[] = [];

    // Core validation checks
    if (!content.includes('TLSv1.3')) {
      errors.push('Missing TLS 1.3 protocol declaration');
    }
    if (!content.includes('http2')) {
      errors.push('Missing HTTP/2 protocol declaration');
    }
    if (!content.includes('limit_req_zone')) {
      errors.push('Missing limit_req_zone rate-limiting configuration');
    }
    if (!content.includes('limit_req zone=')) {
      errors.push('Missing limit_req directive in API routing block');
    }
    if (!content.includes('proxy_set_header Upgrade $http_upgrade;')) {
      errors.push('Missing WebSocket Upgrade header');
    }
    if (!content.includes('proxy_set_header Connection "upgrade";')) {
      errors.push('Missing WebSocket Connection upgrade directive');
    }
    if (!content.includes('Strict-Transport-Security')) {
      warnings.push('HSTS header is recommended for production SSL compliance');
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
    };
  }

  public getSummary(): {
    domainName: string;
    upstream: string;
    tlsVersions: string[];
    rateLimit: string;
    wsPath: string;
  } {
    return {
      domainName: this.domainName,
      upstream: `${this.upstreamHost}:${this.upstreamPort}`,
      tlsVersions: ['TLSv1.2', 'TLSv1.3'],
      rateLimit: `${this.rateLimitReqPerSec}r/s (burst=${this.rateLimitBurst})`,
      wsPath: this.webSocketPath,
    };
  }
}
