/**
 * Production Automated Offsite Backup Cron Script Generator
 * Generates secure bash scripts and crontab specifications featuring PostgreSQL dump,
 * AES-256 PBKDF2 payload encryption, remote vault synchronization (rclone / S3),
 * and automated retention lifecycle management.
 */

export interface BackupCronOptions {
  cronSchedule?: string;
  backupDir?: string;
  databaseName?: string;
  dbUser?: string;
  encryptionPassphrase?: string;
  remoteVaultTarget?: string;
  retentionDays?: number;
  alertEmail?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export class OffsiteBackupCron {
  private cronSchedule: string;
  private backupDir: string;
  private databaseName: string;
  private dbUser: string;
  private encryptionPassphrase: string;
  private remoteVaultTarget: string;
  private retentionDays: number;
  private alertEmail: string;

  constructor(options: BackupCronOptions = {}) {
    this.cronSchedule = options.cronSchedule || '0 2 * * *'; // Daily at 02:00 AM
    this.backupDir = options.backupDir || '/var/backups/clinicore';
    this.databaseName = options.databaseName || 'clinicore_prod';
    this.dbUser = options.dbUser || 'clinicore_admin';
    this.encryptionPassphrase = options.encryptionPassphrase || 'CLINICORE_ENCRYPTION_SECRET_VAULT_KEY_2026';
    this.remoteVaultTarget = options.remoteVaultTarget || 'remote_vault:clinicore-offsite-backups';
    this.retentionDays = options.retentionDays || 30;
    this.alertEmail = options.alertEmail || 'admin@clinicflow.pk';
  }

  public generateBackupScript(): string {
    return `#!/usr/bin/env bash
# ==============================================================================
# ClinicFlow Automated AES-256 Encrypted Offsite Backup Engine
# Auto-generated by OffsiteBackupCron
# ==============================================================================

set -euo pipefail

# Configuration Parameters
BACKUP_DIR="${this.backupDir}"
DB_NAME="${this.databaseName}"
DB_USER="${this.dbUser}"
REMOTE_VAULT="${this.remoteVaultTarget}"
RETENTION_DAYS=${this.retentionDays}
PASSPHRASE="${this.encryptionPassphrase}"
ALERT_EMAIL="${this.alertEmail}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

RAW_BACKUP_FILE="\${BACKUP_DIR}/\${DB_NAME}_\${TIMESTAMP}.sql.gz"
ENCRYPTED_BACKUP_FILE="\${RAW_BACKUP_FILE}.enc"

# Ensure Local Backup Target Exists
mkdir -p "\${BACKUP_DIR}"

echo "[$(date)] 🚀 Starting production backup for \${DB_NAME}..."

# Step 1: Execute Compressed PostgreSQL Database Dump
if pg_dump -U "\${DB_USER}" -h localhost -d "\${DB_NAME}" --format=custom --compress=9 > "\${RAW_BACKUP_FILE}"; then
    echo "[$(date)] ✅ Database dump successful: \${RAW_BACKUP_FILE}"
else
    echo "[$(date)] ❌ CRITICAL: Database dump failed!" | mail -s "ClinicFlow Backup Failure Alert" "\${ALERT_EMAIL}" || true
    exit 1
fi

# Step 2: Perform Enterprise AES-256 Encryption (PBKDF2)
echo "[$(date)] 🔐 Encrypting database backup payload using AES-256-CBC..."
if openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -in "\${RAW_BACKUP_FILE}" -out "\${ENCRYPTED_BACKUP_FILE}" -k "\${PASSPHRASE}"; then
    echo "[$(date)] ✅ Encryption successful: \${ENCRYPTED_BACKUP_FILE}"
    rm -f "\${RAW_BACKUP_FILE}"
else
    echo "[$(date)] ❌ CRITICAL: Payload encryption failed!"
    rm -f "\${RAW_BACKUP_FILE}"
    exit 1
fi

# Step 3: Synchronize Encrypted Artifact to Remote Offsite Vault
echo "[$(date)] ☁️ Uploading encrypted payload to remote vault (\${REMOTE_VAULT})..."
if rclone copy "\${ENCRYPTED_BACKUP_FILE}" "\${REMOTE_VAULT}" --transfers 4 --retries 3; then
    echo "[$(date)] ✅ Offsite sync completed cleanly."
else
    echo "[$(date)] ⚠️ WARNING: Offsite vault sync failed!"
fi

# Step 4: Execute Retention Policy Cleanup
echo "[$(date)] 🧹 Purging local backups older than \${RETENTION_DAYS} days..."
find "\${BACKUP_DIR}" -type f -name "*.enc" -mtime +\${RETENTION_DAYS} -delete

echo "[$(date)] 🎉 Backup cycle finished successfully."
`;
  }

  public generateCrontabEntry(): string {
    return `${this.cronSchedule} /bin/bash /opt/clinicore/scripts/clinicore_offsite_backup.sh >> /var/log/clinicore_backup.log 2>&1`;
  }

  public validateBackupScript(scriptContent?: string): ValidationResult {
    const content = scriptContent || this.generateBackupScript();
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!content.includes('openssl enc -aes-256-cbc')) {
      errors.push('Missing AES-256 encryption command');
    }
    if (!content.includes('-pbkdf2')) {
      errors.push('Missing PBKDF2 key derivation parameter for OpenSSL AES-256');
    }
    if (!content.includes('pg_dump')) {
      errors.push('Missing pg_dump database dump command');
    }
    if (!content.includes('rclone') && !content.includes('aws s3') && !content.includes('rsync')) {
      warnings.push('No recognized remote sync binary (rclone/aws s3/rsync) found in script');
    }
    if (!content.includes('find') || !content.includes('-mtime')) {
      warnings.push('Retention policy cleanup command missing or incomplete');
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
    };
  }

  public getSummary(): {
    cronSchedule: string;
    encryption: string;
    remoteVault: string;
    retentionDays: number;
  } {
    return {
      cronSchedule: this.cronSchedule,
      encryption: 'AES-256-CBC (PBKDF2 iter=100000)',
      remoteVault: this.remoteVaultTarget,
      retentionDays: this.retentionDays,
    };
  }
}
